# encoding: utf-8

# Todas las provincias de España
Provincia.create(:id => 1, :nombre => 'Álava');
Provincia.create(:id => 2, :nombre => 'Albacete');
Provincia.create(:id => 3, :nombre => 'Alicante');
Provincia.create(:id => 4, :nombre => 'Almería');
Provincia.create(:id => 5, :nombre => 'Avila');
Provincia.create(:id => 6, :nombre => 'Badajoz');
Provincia.create(:id => 7, :nombre => 'Illes Baleares');
Provincia.create(:id => 8, :nombre => 'Barcelona');
Provincia.create(:id => 9, :nombre => 'Burgos');
Provincia.create(:id => 10, :nombre => 'Cáceres');
Provincia.create(:id => 11, :nombre => 'Cádiz');
Provincia.create(:id => 12, :nombre => 'Cástellón');
Provincia.create(:id => 13, :nombre => 'Ciudad Real');
Provincia.create(:id => 14, :nombre => 'Córdoba');
Provincia.create(:id => 15, :nombre => 'Coruña, A');
Provincia.create(:id => 16, :nombre => 'Cuenca');
Provincia.create(:id => 17, :nombre => 'Girona');
Provincia.create(:id => 18, :nombre => 'Granada');
Provincia.create(:id => 19, :nombre => 'Guadalajara');
Provincia.create(:id => 20, :nombre => 'Guipuzcoa');
Provincia.create(:id => 21, :nombre => 'Huelva');
Provincia.create(:id => 22, :nombre => 'Huesca');
Provincia.create(:id => 23, :nombre => 'Jaén');
Provincia.create(:id => 24, :nombre => 'León');
Provincia.create(:id => 25, :nombre => 'Lleida');
Provincia.create(:id => 26, :nombre => 'Rioja, La');
Provincia.create(:id => 27, :nombre => 'Lugo');
Provincia.create(:id => 28, :nombre => 'Madrid');
Provincia.create(:id => 29, :nombre => 'Málaga');
Provincia.create(:id => 30, :nombre => 'Murcia');
Provincia.create(:id => 31, :nombre => 'Navarra');
Provincia.create(:id => 32, :nombre => 'Ourense');
Provincia.create(:id => 33, :nombre => 'Asturias');
Provincia.create(:id => 34, :nombre => 'Palencia');
Provincia.create(:id => 35, :nombre => 'Palmas, Las');
Provincia.create(:id => 36, :nombre => 'Pontevedra');
Provincia.create(:id => 37, :nombre => 'Salamanca');
Provincia.create(:id => 38, :nombre => 'Santa Cruz de Tenerife');
Provincia.create(:id => 39, :nombre => 'Cantabria');
Provincia.create(:id => 40, :nombre => 'Segovia');
Provincia.create(:id => 41, :nombre => 'Sevilla');
Provincia.create(:id => 42, :nombre => 'Soria');
Provincia.create(:id => 43, :nombre => 'Tarragona');
Provincia.create(:id => 44, :nombre => 'Teruel');
Provincia.create(:id => 45, :nombre => 'Toledo');
Provincia.create(:id => 46, :nombre => 'Valencia');
Provincia.create(:id => 47, :nombre => 'Valladolid');
Provincia.create(:id => 48, :nombre => 'Vizcaya');
Provincia.create(:id => 49, :nombre => 'Zamora');
Provincia.create(:id => 50, :nombre => 'Zaragoza');
Provincia.create(:id => 51, :nombre => 'Ceuta');
Provincia.create(:id => 52, :nombre => 'Melilla');